export const PREVIOUS_API_DATA_KEY = "PREVIOUS_API_DATA_KEY";
export const CHANGELOG_KEY = "CHANGELOG_KEY";
export const LAST_CHECK_KEY = "LAST_CHECK_KEY";

export const ALARM_INTERVAL_MIN = 60;

export const RED_BADGE_COLOR = "#e81313";
