export const PREVIOUS_EXTENSIONS_STATE_KEY = "PREVIOUS_EXTENSIONS_STATE_KEY";
export const CHANGELOG_KEY = "CHANGELOG_KEY";
export const LAST_CHECK_KEY = "LAST_CHECK_KEY";
export const FETCH_ERRORS_KEY = "FETCH_ERRORS_KEY";
export const CHECK_PROGRESS_KEY = "CHECK_PROGRESS_KEY";
export const CHECK_IN_PROGRESS_KEY = "CHECK_IN_PROGRESS_KEY";

export const TRIGGER_CHECK_ACTION = "TRIGGER_CHECK";
export const RETRY_EXTENSION_ACTION = "RETRY_EXTENSION";

export const NON_RETRYABLE_ERRORS = [
  "Could not find canonical link in page",
];

export const ALARM_INTERVAL_MIN = 60;

export const RED_BADGE_COLOR = "#e81313";
